version: '3'

services:
  app:
    image: test
    #    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    #    container_name: 'spring_course-1.0-SNAPSHOT-plain'
    #    environment:
    #      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/users
    #      - SPRING_DATASOURCE_USERNAME=postgres
    #      - SPRING_DATASOURCE_PASSWORD=postgres
    #      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    depends_on:
      - pg

  pg:
    #    restart: always
    image: postgres:14.3-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
#      PGDATA: /var/lib/postgresql/data/pgdata