db:
  username: postgres
  password: postgres
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost


  pool:
    size: 10
    timeout: 12
  pools:
    - size: 1
      timeout: 2
    - size: 2
      timeout: 3

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/spring_test
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate

logging:
  level:
    root: INFO
    com.plaxa.spring_course.repository: INFO
  file:
    name: plaxa.log
    path: /

